backend:
  name: github
  repo: casiycomo/casiymedio
  branch: main
  base_url: moonlit-choux-a813cd.netlify.app
  auth_endpoint: auth

media_folder: "imagenes"
public_folder: "/imagenes"

locale: es

collections:
  - name: "articulos"
    label: "Artículos"
    folder: "articulos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título",   name: "titulo",  widget: "string" }
      - { label: "Autor/a",  name: "autor",   widget: "string" }
      - label: "Sección"
        name: "seccion"
        widget: "select"
        options:
          - { label: "Pantalla",       value: "Pantalla" }
          - { label: "Conversaciones", value: "Conversaciones" }
          - { label: "Paranoia",       value: "Paranoia" }
          - { label: "Ruidos",         value: "Ruidos" }
          - { label: "Miopía",         value: "Miopía" }
          - { label: "Hedor",          value: "Hedor" }
      - { label: "Fecha", name: "fecha", widget: "datetime", format: "YYYY-MM-DD", date_format: "DD/MM/YYYY", time_format: false }
      - { label: "Imagen", name: "imagen", widget: "image", required: false }
      - { label: "Extracto", name: "extracto", widget: "text", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - { label: "Publicado", name: "publicado", widget: "boolean", default: true }
      - { label: "Orden", name: "orden", widget: "number", default: 0 }
